In [78]:
import pandas as pd
from flask import Flask, jsonify

app = Flask(__name__)

# Homepage padrão da API "Site"
@app.route('/')
def homepage():
    return 'A API está no ar'

# Pagina somente do total de vendas da tabela utilizada na API
@app.route('/dados')
def totalvendas():
    tabela = pd.read_csv('api.csv')
    total_vendas = tabela ['Vendas'].sum()
    resposta = {'total_vendas' : total_vendas}
    return jsonify(resposta)

# Página da tabela utilizada na API completa convertida em dicionário
@app.route('/tabela')
def tabelaapi():
    dict_from_csv = pd.read_csv('api.csv', header=0, index_col=0, squeeze=True).to_dict()
    return jsonify(dict_from_csv)

# Criação de um dicionário aleatório para teste
@app.route('/tabelateste')
def dados():
    tabela2 = [
    {'id': 0,
     'title': 'A Fire Upon the Deep',
     'author': 'Vernor Vinge',
     'first_sentence': 'The coldsleep itself was dreamless.',
     'year_published': '1992'},
    {'id': 1,
     'title': 'The Ones Who Walk Away From Omelas',
     'author': 'Ursula K. Le Guin',
     'first_sentence': 'With a clamor of bells that set the swallows soaring, the Festival of Summer came to the city Omelas, bright-towered by the sea.',
     'published': '1973'},
    {'id': 2,
     'title': 'Dhalgren',
     'author': 'Samuel R. Delany',
     'first_sentence': 'to wound the autumnal city.',
     'published': '1975'}
]
   
    return jsonify(tabela2)

app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [11/Jan/2022 15:25:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Jan/2022 15:25:24] "GET /tabela HTTP/1.1" 200 -
127.0.0.1 - - [11/Jan/2022 15:25:43] "GET /tabela HTTP/1.1" 200 -
127.0.0.1 - - [11/Jan/2022 15:25:48] "GET /tabela HTTP/1.1" 200 -

In [84]:
display(tabela)

        TV  Radio  Jornal  Vendas
0    230.1   37.8    69.2    22.1
1     44.5   39.3    45.1    10.4
2     17.2   45.9    69.3    12.0
3    151.5   41.3    58.5    16.5
4    180.8   10.8    58.4    17.9
..     ...    ...     ...     ...
195   38.2    3.7    13.8     7.6
196   94.2    4.9     8.1    14.0
197  177.0    9.3     6.4    14.8
198  283.6   42.0    66.2    25.5
199  232.1    8.6     8.7    18.4

[200 rows x 4 columns]

In [83]:
dict_from_csv = pd.read_csv('api.csv', header=None, index_col=0, squeeze=True).to_dict()
print(dict_from_csv)

{1: {'TV': 'Radio', '230.1': '37.8', '44.5': '39.3', '17.2': '4.1', '151.5': '41.3', '180.8': '10.8', '8.7': '48.9', '57.5': '32.8', '120.2': '19.6', '8.6': '2.1', '199.8': '3.1', '66.1': '5.8', '214.7': '24', '23.8': '35.1', '97.5': '7.6', '204.1': '32.9', '195.4': '47.7', '67.8': '36.6', '281.4': '39.6', '69.2': '20.5', '147.3': '23.9', '218.4': '27.7', '237.4': '27.5', '13.2': '15.9', '228.3': '16.9', '62.3': '12.6', '262.9': '3.5', '142.9': '29.3', '240.1': '7.3', '248.8': '27.1', '70.6': '16', '292.9': '28.3', '112.9': '17.4', '97.2': '1.5', '265.6': '20', '95.7': '1.4', '290.7': '4.1', '266.9': '43.8', '74.7': '49.4', '43.1': '26.7', '228': '37.7', '202.5': '22.3', '177': '9.3', '293.6': '27.7', '206.9': '8.4', '25.1': '25.7', '175.1': '22.5', '89.7': '9.9', '239.9': '41.5', '227.2': '15.8', '66.9': '11.7', '100.4': '9.6', '216.4': '41.7', '182.6': '46.2', '262.7': '28.8', '198.9': '49.4', '7.3': '28.1', '136.2': '19.2', '210.8': '49.6', '210.7': '29.5', '53.5': '2', '261.3': '42.7', '239.3': '15.5', '102.7': '29.6', '131.1': '42.8', '69': '9.3', '31.5': '24.6', '139.3': '14.5', '216.8': '43.9', '199.1': '30.6', '109.8': '47.8', '26.8': '33', '129.4': '5.7', '213.4': '24.6', '16.9': '43.7', '27.5': '1.6', '120.5': '28.5', '5.4': '29.9', '116': '7.7', '76.4': '0.8', '239.8': '4.1', '75.3': '20.3', '68.4': '44.5', '213.5': '43', '193.2': '18.4', '76.3': '27.5', '110.7': '40.6', '88.3': '25.5', '134.3': '4.9', '28.6': '1.5', '217.7': '33.5', '250.9': '36.5', '107.4': '14', '163.3': '31.6', '197.6': '23.3', '184.9': '43.9', '289.7': '42.3', '135.2': '41.7', '222.4': '3.4', '296.4': '36.3', '280.2': '10.1', '187.9': '17.2', '238.2': '34.3', '137.9': '46.4', '25': '11', '90.4': '0.3', '13.1': '0.4', '255.4': '26.9', '225.8': '8.2', '241.7': '38', '175.7': '15.4', '209.6': '20.6', '78.2': '46.8', '75.1': '35', '139.2': '14.3', '125.7': '36.9', '19.4': '16', '141.3': '26.8', '18.8': '21.7', '224': '2.4', '123.1': '34.6', '229.5': '32.3', '87.2': '11.8', '7.8': '38.9', '80.2': '0', '220.3': '49', '59.6': '12', '0.7': '39.6', '265.2': '2.9', '8.4': '27.2', '219.8': '33.5', '36.9': '38.6', '48.3': '47', '25.6': '39', '273.7': '28.9', '43': '25.9', '73.4': '17', '193.7': '35.4', '220.5': '33.2', '104.6': '5.7', '96.2': '14.8', '140.3': '1.9', '243.2': '49', '38': '40.3', '44.7': '25.8', '280.7': '13.9', '121': '8.4', '171.3': '39.7', '187.8': '21.1', '4.1': '11.6', '93.9': '43.5', '149.8': '1.3', '11.7': '36.9', '131.7': '18.4', '172.5': '18.1', '85.7': '35.8', '188.4': '18.1', '163.5': '36.8', '117.2': '14.7', '234.5': '3.4', '17.9': '37.6', '206.8': '5.2', '215.4': '23.6', '284.3': '10.6', '50': '11.6', '164.5': '20.9', '19.6': '20.1', '168.4': '7.1', '276.9': '48.9', '248.4': '30.2', '170.2': '7.8', '276.7': '2.3', '165.6': '10', '156.6': '2.6', '218.5': '5.4', '56.2': '5.7', '287.6': '43', '253.8': '21.3', '205': '45.1', '139.5': '2.1', '191.1': '28.7', '286': '13.9', '18.7': '12.1', '39.5': '41.1', '75.5': '10.8', '166.8': '42', '149.7': '35.6', '38.2': '3.7', '94.2': '4.9', '283.6': '42', '232.1': '8.6'}, 2: {'TV': 'Jornal', '230.1': '69.2', '44.5': '45.1', '17.2': '31.6', '151.5': '58.5', '180.8': '58.4', '8.7': '75', '57.5': '23.5', '120.2': '11.6', '8.6': '1', '199.8': '34.6', '66.1': '24.2', '214.7': '4', '23.8': '65.9', '97.5': '7.2', '204.1': '46', '195.4': '52.9', '67.8': '114', '281.4': '55.8', '69.2': '18.3', '147.3': '19.1', '218.4': '53.4', '237.4': '11', '13.2': '49.6', '228.3': '26.2', '62.3': '18.3', '262.9': '19.5', '142.9': '12.6', '240.1': '8.7', '248.8': '22.9', '70.6': '40.8', '292.9': '43.2', '112.9': '38.6', '97.2': '30', '265.6': '0.3', '95.7': '7.4', '290.7': '8.5', '266.9': '5', '74.7': '45.7', '43.1': '35.1', '228': '32', '202.5': '31.6', '177': '6.4', '293.6': '1.8', '206.9': '26.4', '25.1': '43.3', '175.1': '31.5', '89.7': '35.7', '239.9': '18.5', '227.2': '49.9', '66.9': '36.8', '100.4': '3.6', '216.4': '39.6', '182.6': '58.7', '262.7': '15.9', '198.9': '60', '7.3': '41.4', '136.2': '16.6', '210.8': '37.7', '210.7': '9.3', '53.5': '21.4', '261.3': '54.7', '239.3': '27.3', '102.7': '8.4', '131.1': '28.9', '69': '0.9', '31.5': '2.2', '139.3': '10.2', '216.8': '27.2', '199.1': '38.7', '109.8': '51.4', '26.8': '19.3', '129.4': '31.3', '213.4': '13.1', '16.9': '89.4', '27.5': '20.7', '120.5': '14.2', '5.4': '9.4', '116': '23.1', '76.4': '14.8', '239.8': '36.9', '75.3': '32.5', '68.4': '35.6', '213.5': '33.8', '193.2': '65.7', '76.3': '16', '110.7': '63.2', '88.3': '73.4', '134.3': '9.3', '28.6': '33', '217.7': '59', '250.9': '72.3', '107.4': '10.9', '163.3': '52.9', '197.6': '14.2', '184.9': '1.7', '289.7': '51.2', '135.2': '45.9', '222.4': '13.1', '296.4': '100.9', '280.2': '21.4', '187.9': '17.9', '238.2': '5.3', '137.9': '59', '25': '29.7', '90.4': '23.2', '13.1': '25.6', '255.4': '5.5', '225.8': '56.5', '241.7': '23.2', '175.7': '2.4', '209.6': '10.7', '78.2': '34.5', '75.1': '52.7', '139.2': '25.6', '125.7': '79.2', '19.4': '22.3', '141.3': '46.2', '18.8': '50.4', '224': '15.6', '123.1': '12.4', '229.5': '74.2', '87.2': '25.9', '7.8': '50.6', '80.2': '9.2', '220.3': '3.2', '59.6': '43.1', '0.7': '8.7', '265.2': '43', '8.4': '2.1', '219.8': '45.1', '36.9': '65.6', '48.3': '8.5', '25.6': '9.3', '273.7': '59.7', '43': '20.5', '73.4': '12.9', '193.7': '75.6', '220.5': '37.9', '104.6': '34.4', '96.2': '38.9', '140.3': '9', '243.2': '44.3', '38': '11.9', '44.7': '20.6', '280.7': '37', '121': '48.7', '171.3': '37.7', '187.8': '9.5', '4.1': '5.7', '93.9': '50.5', '149.8': '24.3', '11.7': '45.2', '131.7': '34.6', '172.5': '30.7', '85.7': '49.3', '188.4': '25.6', '163.5': '7.4', '117.2': '5.4', '234.5': '84.8', '17.9': '21.6', '206.8': '19.4', '215.4': '57.6', '284.3': '6.4', '50': '18.4', '164.5': '47.4', '19.6': '17', '168.4': '12.8', '276.9': '41.8', '248.4': '20.3', '170.2': '35.2', '276.7': '23.7', '165.6': '17.6', '156.6': '8.3', '218.5': '27.4', '56.2': '29.7', '287.6': '71.8', '253.8': '30', '205': '19.6', '139.5': '26.6', '191.1': '18.2', '286': '3.7', '18.7': '23.4', '39.5': '5.8', '75.5': '6', '166.8': '3.6', '149.7': '6', '38.2': '13.8', '94.2': '8.1', '283.6': '66.2', '232.1': '8.7'}, 3: {'TV': 'Vendas', '230.1': '22.1', '44.5': '10.4', '17.2': '5.9', '151.5': '16.5', '180.8': '17.9', '8.7': '7.2', '57.5': '11.8', '120.2': '13.2', '8.6': '4.8', '199.8': '16.4', '66.1': '12.6', '214.7': '17.4', '23.8': '9.2', '97.5': '13.7', '204.1': '19', '195.4': '22.4', '67.8': '12.5', '281.4': '24.4', '69.2': '11.3', '147.3': '14.6', '218.4': '18', '237.4': '18.9', '13.2': '5.6', '228.3': '20.5', '62.3': '9.7', '262.9': '17', '142.9': '15', '240.1': '18.2', '248.8': '18.9', '70.6': '10.5', '292.9': '21.4', '112.9': '11.9', '97.2': '13.2', '265.6': '17.4', '95.7': '11.9', '290.7': '17.8', '266.9': '25.4', '74.7': '14.7', '43.1': '10.1', '228': '21.5', '202.5': '16.6', '177': '14.8', '293.6': '20.7', '206.9': '17.9', '25.1': '8.5', '175.1': '16.1', '89.7': '10.6', '239.9': '23.2', '227.2': '19.8', '66.9': '9.7', '100.4': '10.7', '216.4': '22.6', '182.6': '21.2', '262.7': '20.2', '198.9': '23.7', '7.3': '5.5', '136.2': '13.2', '210.8': '23.8', '210.7': '18.4', '53.5': '8.1', '261.3': '24.2', '239.3': '20.7', '102.7': '14', '131.1': '16', '69': '11.3', '31.5': '11', '139.3': '13.4', '216.8': '22.3', '199.1': '18.3', '109.8': '16.7', '26.8': '8.8', '129.4': '11', '213.4': '17', '16.9': '8.7', '27.5': '6.9', '120.5': '14.2', '5.4': '5.3', '116': '11', '76.4': '9.4', '239.8': '17.3', '75.3': '11.3', '68.4': '13.6', '213.5': '21.7', '193.2': '20.2', '76.3': '12', '110.7': '16', '88.3': '12.9', '134.3': '14', '28.6': '7.3', '217.7': '19.4', '250.9': '22.2', '107.4': '11.5', '163.3': '16.9', '197.6': '16.6', '184.9': '20.7', '289.7': '25.4', '135.2': '17.2', '222.4': '16.5', '296.4': '23.8', '280.2': '19.8', '187.9': '19.7', '238.2': '20.7', '137.9': '15', '25': '7.2', '90.4': '12', '13.1': '5.3', '255.4': '19.8', '225.8': '18.4', '241.7': '21.8', '175.7': '17.1', '209.6': '20.9', '78.2': '14.6', '75.1': '12.6', '139.2': '12.2', '125.7': '15.9', '19.4': '6.6', '141.3': '15.5', '18.8': '7', '224': '16.6', '123.1': '15.2', '229.5': '19.7', '87.2': '10.6', '7.8': '6.6', '80.2': '11.9', '220.3': '24.7', '59.6': '9.7', '0.7': '1.6', '265.2': '17.7', '8.4': '5.7', '219.8': '19.6', '36.9': '10.8', '48.3': '11.6', '25.6': '9.5', '273.7': '20.8', '43': '9.6', '73.4': '10.9', '193.7': '19.2', '220.5': '20.1', '104.6': '10.4', '96.2': '12.3', '140.3': '10.3', '243.2': '25.4', '38': '10.9', '44.7': '10.1', '280.7': '16.1', '121': '11.6', '171.3': '16', '187.8': '20.6', '4.1': '3.2', '93.9': '15.3', '149.8': '10.1', '11.7': '7.3', '131.7': '12.9', '172.5': '16.4', '85.7': '13.3', '188.4': '19.9', '163.5': '18', '117.2': '11.9', '234.5': '16.9', '17.9': '8', '206.8': '17.2', '215.4': '17.1', '284.3': '20', '50': '8.4', '164.5': '17.5', '19.6': '7.6', '168.4': '16.7', '276.9': '27', '248.4': '20.2', '170.2': '16.7', '276.7': '16.8', '165.6': '17.6', '156.6': '15.5', '218.5': '17.2', '56.2': '8.7', '287.6': '26.2', '253.8': '17.6', '205': '22.6', '139.5': '10.3', '191.1': '17.3', '286': '20.9', '18.7': '6.7', '39.5': '10.8', '75.5': '11.9', '166.8': '19.6', '149.7': '17.3', '38.2': '7.6', '94.2': '14', '283.6': '25.5', '232.1': '18.4'}}